name: Build and Publish to NPM

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Verify dependencies
      run: |
        npm ls --depth=0
        echo "Node version: $(node --version)"
        echo "NPM version: $(npm --version)"
      
    - name: Build library
      run: npm run build
      
    - name: Verify library build
      run: |
        if [ ! -d "dist/ng-tables" ]; then
          echo "Error: Library build failed - dist/ng-tables directory not found"
          exit 1
        fi
        echo "Library build successful - dist directory contents:"
        ls -la dist/ng-tables/
      
    - name: Verify test files
      run: |
        echo "Test files found:"
        find test -name "*.spec.ts" -exec echo "  {}" \;
        if [ $(find test -name "*.spec.ts" | wc -l) -eq 0 ]; then
          echo "Error: No test files found in test directory"
          exit 1
        fi
        echo "Test configuration:"
        cat test/tsconfig.spec.json
        echo "Angular test configuration:"
        cat angular.json | grep -A 10 -B 2 '"test":'
      
    - name: Run tests
      run: npm run test:ci
      
    - name: Build sample app
      run: npm run build:sample

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build library
      run: npm run build
      
    - name: Publish to NPM
      run: npm publish dist/ng-tables
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  deploy-pages:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write
      
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build sample app for GitHub Pages
      run: npm run build:sample:prod
      
    - name: Verify build output
      run: |
        echo "Build output structure:"
        ls -la dist/sample/
        echo "Browser directory contents:"
        ls -la dist/sample/browser/
        echo "Index.html content:"
        cat dist/sample/browser/index.html
      
    - name: Setup Pages
      uses: actions/configure-pages@v5
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist/sample/browser'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4